import { Blog } from "@/types/blog";

const breadsGemstoneData: Blog[] = [
  {
    id: 1,
    title: "Laxmi Narashimha Shaligram",
    paragraph: "",
    image: "/images/gemstone/085.jpg",
    author: {
      name: "Laxmi Narashimha Shaligram",
      image: "/images/breads/author-01.png",
      designation: "Free Cash On Delivery",
    },
    tags: ["new"],
    publishDate: "$ 350",
  },
  {
    id: 2,
    title: "Shaligram",
    paragraph: "",
    image: "/images/gemstone/136.jpg",
    author: {
      name: "Shaligram",
      image: "/images/blog/author-02.png",
      designation: "Free Cash On Delivery",
    },
    tags: ["design"],
    publishDate: "$ 350",
  },
  {
    id: 3,
    title: "Shaligram",
    paragraph: "",
    image: "/images/gemstone/150.jpg",
    author: {
      name: "Shaligram",
      image: "/images/blog/author-03.png",
      designation: "Free Cash On Delivery",
    },
    tags: ["design"],
    publishDate: "$ 550",
  },
  {
    id: 4,
    title: "Shaligram",
    paragraph: "",
    image: "/images/gemstone/164.jpg",
    author: {
      name: "Shaligram",
      image: "/images/blog/author-03.png",
      designation: "Free Cash On Delivery",
    },
    tags: ["design"],
    publishDate: "$ 750",
  },
  {
    id: 5,
    title: "Krishna Shaligram",
    paragraph: "",
    image: "/images/gemstone/180.jpg",
    author: {
      name: "Krishna Shaligram",
      image: "/images/blog/author-03.png",
      designation: "Free Cash On Delivery",
    },
    tags: ["design"],
    publishDate: "$ 350",
  },
  {
    id: 6,
    title: "Shaligram",
    paragraph: "",
    image: "/images/gemstone/194.jpg",
    author: {
      name: "Shaligram",
      image: "/images/blog/author-03.png",
      designation: "Free Cash On Delivery",
    },
    tags: ["design"],
    publishDate: "$ 350",
  },
  {
    id: 7,
    title: "Laxmi Narashimha Shaligram",
    paragraph: "",
    image: "/images/gemstone/207.jpg",
    author: {
      name: "Laxmi Narashimha Shaligram",
      image: "/images/blog/author-03.png",
      designation: "Free Cash On Delivery",
    },
    tags: ["design"],
    publishDate: "$ 350",
  },
  {
    id: 8,
    title: "Shaligram",
    paragraph: "",
    image: "/images/gemstone/219.jpg",
    author: {
      name: "Shaligram",
      image: "/images/blog/author-03.png",
      designation: "Free Cash On Delivery",
    },
    tags: ["design"],
    publishDate: "$ 350",
  },
  {
    id: 9,
    title: "Shaligram",
    paragraph: "",
    image: "/images/gemstone/232.jpg",
    author: {
      name: "Shaligram",
      image: "/images/blog/author-03.png",
      designation: "Free Cash On Delivery",
    },
    tags: ["design"],
    publishDate: "$ 350",
  },
  {
    id: 10,
    title: "Varaha Shaligram",
    paragraph: "",
    image: "/images/gemstone/245.jpg",
    author: {
      name: "Varaha Shaligram",
      image: "/images/blog/author-03.png",
      designation: "Free Cash On Delivery",
    },
    tags: ["design"],
    publishDate: "$ 620",
  },
  {
    id: 11,
    title: "Krishna Shaligram",
    paragraph: "",
    image: "/images/gemstone/259.jpg",
    author: {
      name: "Krishna Shaligram",
      image: "/images/blog/author-03.png",
      designation: "Free Cash On Delivery",
    },
    tags: ["design"],
    publishDate: "$ 550",
  },
];
export default breadsGemstoneData;
